### ISSUE TITLE
Not clear how to use "list" subcommand, or what it effectively does

### ISSUE THREAD

**Issue by arunsathiya** [envio-cli/envio#14]
It'd be helpful to describe how the "list" subcommand is used/what it actually does. 

At this time, `envio list --help` says `List all the environment variables in a profile or all the profiles` which gives me the impression that it lists out all the environment variables associated with all profiles, but it actually does the following:

- `envio list` alone results in `Invalid number of arguments` error, because the command expects a profile name, or the string `profiles` to list out all the profiles. This improvement is being explored in https://github.com/humblepenguinn/envio/issues/2
- `envio list profileName` or `envio list profiles` results  in listing of environment variables associated with the particular profile (in this example, named `profileName`) or all profile names.

I think, overall, it'd be helpful to branch out `list` into two different commands; `list-profiles` to list all the profiles, and `list-envvars profileName` to list envvars associated with a profile name.

If it's decided to retain the current approach, it'd perhaps be helpful to explore improving the `Arguments` part of the `--help` output:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/18581859/229975709-06d6f40d-d293-46e7-b066-c12e3e165d5f.png">

**Comment by humblepenguinn** [comment]
The description provided by the `envio list` command, in my opinion, seems well explained to me.

> which gives me the impression that it lists out all the environment variables associated with all profiles

It mentions it lists all the environment variables in a profile not all the environment variables associated with all profiles.  So I do not quite understand how you came to this conclusion.

I also think that the current approach is better rather than breaking `list` into two entirely different sub commands. 

But, yes, you are right it would be helpful to improve the `arguments` part of the `--help` output. I'm thinking of just scarping the help message that `clap` provides and overriding it with a custom one.

Thank you for your feedback! It helps out a lot
