### ISSUE TITLE
Missing build dependencies throws errors

### ISSUE THREAD

**Issue by scottw-kr** [envio-cli/envio#24]
**Describe the bug**
Attempting to follow your install instructions produced errors stating I was missing binaries. I tried building from source and hit the same errors.

**To Reproduce**
1. Run command `cargo install envio`

**Expected behavior**
Should install the app on the target machine.

**Screenshots**
<img width="1301" alt="Screenshot 2023-06-01 at 15 14 51" src="https://github.com/humblepenguinn/envio/assets/80055821/1833c740-38a9-43b6-854c-6aac3923fd61">
<img width="1291" alt="Screenshot 2023-06-01 at 15 15 15" src="https://github.com/humblepenguinn/envio/assets/80055821/95cf2b9f-fa0b-4f27-9646-035cc01eb45d">

**Device (please complete the following information):**
 - OS: macOS Ventura
 - Shell: zsh
 - CLI Version: ??? `envio 0.5.0`

**Additional context**
I had to run these installers to get it to install

```zsh
brew install libgpg-error
brew install gpgme
```

**Comment by scottw-kr** [comment]
Oh, it's listed out as a dependency on the https://humblepenguinn.github.io/envio/encryption-types/#gpg page. Maybe just mention that on the Instillation page, or figure out a way to complete an install without GPG if the user isn't planning on using GPG.

**Comment by scottw-kr** [comment]
Is it normal behavior for the same terminal tool (Warp) require entering the password every time you open a new terminal? I was hoping that this would help secure my dev environment, but if I have to enter the password every time I open _any_ new terminal windows, that's kind of a pain. Can I set it to only ask for the password on `load`?

**Comment by humblepenguinn** [comment]
Whenever you open a new terminal session, `envio` decrypts the profile that you set to load and imports all the envs. So if you used plain passphrase encryption then you need to provide the password every time you open a new terminal session. If you do not want to use a password then you can use `gpg` encryption. You won't have to provide the passphrase every time you open a new terminal session.

Regarding your question, if you can set `envio` to only ask the password on load, I mean it is possible to implement something like that, but that would just make your envs vulnerable since `envio` needs to store your passphrase somewhere. I might be shortsighted here, If you have any suggestions as to how we can fix this issue then its something I might consider.

**Comment by humblepenguinn** [comment]
> Oh, it's listed out as a dependency on the https://humblepenguinn.github.io/envio/encryption-types/#gpg page. Maybe just mention that on the Instillation page, or figure out a way to complete an install without GPG if the user isn't planning on using GPG.

Thats my bad, I'll fix that
