### ISSUE TITLE
GPG based profile prompts for encryption key

### ISSUE THREAD

**Issue by afh** [envio-cli/envio#36]
**Describe the bug**
envio asks for encryption key for GPG based profile

**To Reproduce**

1. Create a new profile using a GnuPG ID
```sh
envio$ ./target/debug/envio create gpg -g $GPG_ID
Success: Profile created
```
2. Add a new variable to the newly created profile
```sh
envio$ ./target/debug/envio add --keys foo gpg
Loading Profile
Enter your encryption key
? Enter your encryption key:
[OH NO! you forgot your key! just kidding... or did you?]
```

**Expected behavior**
I'd expect the GnuPG Pinentry programm to ask for the passphrase of the key
instead of envio asking for an encryption key.

**Screenshots**
**N/A** ~~If applicable, add screenshots to help explain your problem.~~

**Device (please complete the following information):**
 - OS: macOS 14.3.1 (23D60)
 - Shell: zsh
 - CLI Version: 0.5.0

**Additional context**
I might be missing something in regards how to properly use envio with GnuPG, yet expectation is: I tell envio which GnuPG key to use and envio then relays all passphrase/pin input to GnuPG and Pinentry.
What am I missing?

**Comment by humblepenguinn** [comment]
This seems weird, I just tested it on my machine thinking the commits I just made broke something, however everything seems to work. I tried passing in a invalid fingerprint but even in that case the CLI spits out an error. 

Could you try the following 
```bash
envio create test -g select
```

`envio` will now give you a list of the available gpg keys on your system. Select the one you want to use and then check if it prompts for the passphrase of the key when you add a environment variable.

**Comment by afh** [comment]
I removed the and re-created the profile, this time using `-g select`, yet when adding a new variable envio still asks for an encryption key.

I have an ed25519 key residing on a hardware security token (smart card), could this be an issue?

**Comment by humblepenguinn** [comment]
I believe I might know what the issue is. The way `envio` distinguishes profiles encrypted using gpg or passkey is by checking the first two bytes of the file. 

Currently it checks for the following byte sequence:
```rust
[0x85, 0x01]
```

This byte sequence only exists if the key you used to encrypt was created using the RSA algorithm. If your key pair was generated using a different cryptographic algorithm then the byte sequence changes. So we need to find a different, cross platform, way to distinguish between gpg and passkey encrypted profiles. 

Apologies for the delay, it's been some time since I last took a look at the codebase.

**Comment by humblepenguinn** [comment]
I made a few modifications to the encryption detection function, take a look now and see if it works.

**Comment by afh** [comment]
Something may have broken as I can no longer add environment variables or is it getting too late for me as my 🧠 starts to 💤 

```sh
% ./target/debug/envio create gpg -g $GPG_ID
Success: Profile created
% ./target/debug/envio add --envs foo=bar gpg
error: the following required arguments were not provided:
  <PROFILE_NAME>

Usage: envio add --envs <ENVS>... <PROFILE_NAME>

For more information, try '--help'.
```

**Comment by humblepenguinn** [comment]
Oh yeah sorry, I forgot to mention I changed the usage a bit.

So now you can pass environment variables in the following ways:

```bash
# key value pairs
envio add <profile_name> --envs foo=bar

# we can add multiple key value pairs
envio add <profile_name> --envs foo=bar otherfoo=otherbar

# get envio to prompt for the value of foo
envio add <profile_name> --envs foo

# multiple prompts
envio add <profile_name> --envs foo bar shar
```

You can use a combination of both as well.

The have to ***ensure*** you pass in the profile name first since you can pass in a infinite number of environment variables. So the reason your getting an error is beacuse envio can't find out the profile name. So make sure you pass it in first.

**Comment by humblepenguinn** [comment]
> Something may have broken as I can no longer add environment variables or is it getting too late for me as my 🧠 starts to 💤 
> 
> ```sh
> % ./target/debug/envio create gpg -g $GPG_ID
> Success: Profile created
> % ./target/debug/envio add --envs foo=bar gpg
> error: the following required arguments were not provided:
>   <PROFILE_NAME>
> 
> Usage: envio add --envs <ENVS>... <PROFILE_NAME>
> 
> For more information, try '--help'.
> ```

The CLI tool also kind of misguides the user a bit by putting `<PROFILE_NAME>` after `<ENVS>`. 

I'll get that fixed tomorrow and also update the usage on the website

**Comment by afh** [comment]
Thanks for the clarification; placing the profile name before the `--envs` options works! 🎉 

```sh
% ./target/debug/envio add gpg --envs foo=bar
Applying changes
% ./target/debug/envio launch gpg --program  env | ag foo
foo=bar
```

Indeed the usage info is misleading and it would be helpful to get that changed 🙂
