### ISSUE TITLE
Updated README

### ISSUE THREAD

**Issue by afh** [envio-cli/envio#45]
The commit 5ed5602a2aa44ff654d4eab8f81a70498ca78e98 added a new banner to the project README that promotes a non-technical cause unrelated to the project.

The wording of the banner states _"**We** stand […]"_ and among other folks I am listed by name in the Contributors section in the README, which is likely to be understood that the _**We**_ in the banner includes all Contributors.

Yet, I was not asked whether I agree to be associated with said cause. Understanding the world is complex and controversial I'd much prefer for projects I contribute to stay clear from non-technical topics.

Do think it would be possible for you to show your support for the cause outside of this project?

If not, how can the README or banner be updated to not misrepresent folks, like me, who wish to keep politics and other societal topics out of their open source work due to the often divisive and heated nature?

**Comment by humblepenguinn** [comment]
@afh,

The word "We" was intended to refer to the organization members and not the individual contributors, although I understand the potential for misinterpretation.

I will update the banner to something like "Palestine needs your help" or "Send Aid to Palestine".

However, I won't remove the banner entirely. During the invasion of Ukraine, major open-source projects and companies displayed banners supporting the Ukrainian cause without any notable complaints. If GitHub had taken action to remove those banners and informed people to maintain neutrality in their projects at that time, I wouldn't have put up this banner either. Yet, many projects openly supported the Ukrainian cause without objection. Therefore, if you request the removal of this banner, I expect the same to be applied to every other open-source project.

Moreover, the purpose of the banner is to softly remind individuals of the tragedies caused by this conflict and to show support for those affected. If Israel were facing similar hardships as the Palestinian people, I would display a banner for them as well. 

It's crucial to remember that these aren't just numbers, they're real people with aspirations and dreams, and most tragically, children are being greatly affected by this crisis. Therefore, this banner serves as a call to action to provide aid to the Palestinians affected by this tragedy.

It's easy to remain apolitical from a privileged position, but if we were in the shoes of the Palestinian or Ukrainian people, our stance would likely differ.

Therefore, I can't do more than update the wording of the banner. If you disagree, you're welcome to cease your contributions to this project, and I respect your decision.

**Comment by afh** [comment]
Thank you for your quick response, @humblepenguinn, and detailing your point of view.

Updating the wording of the banner as you propose would help avoid misunderstanding or misrepresentation, thank you. Especially as the [envio-cli](https://github.com/envio-cli) organization currently has no public members (see screenshot below).

The tragedies that are currently unfolding in the world more often than not feel too much to bear and it is important to do what is possible to help and resolve them.
I myself am deeply passionate about various political, societal, and systemic issues, at times driving me to the brink of despair.
I choose to address them in other areas of my life and leave these out of my open source work; others choose to include them. Both are legitimate and equally valid choices.

I'll gladly continue to make contributions to this projects as long as they are welcome and considered useful.

<details><summary>Screenshot of envio-cli organization page</summary>
<img width="997" alt="image" src="https://github.com/envio-cli/envio/assets/16507/b486e706-9c82-4f0f-835a-3ab7b91b5a49">
</details>

**Comment by afh** [comment]
Thank you for updating the README, @humblepenguinn, and going further into the details about your motivation.

Glad to you hear my contributions are valued and appreciated 🙂
